name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lints"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

  test:
    name: "Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Tests
        run: pnpm test

      # For the Try Scenarios
      - id: set-matrix
        run: |
          echo "matrix=$(pnpm -s dlx @embroider/try list)" >> $GITHUB_OUTPUT

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --no-lockfile

      - name: Run Tests
        run: pnpm test

  try-scenarios:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    needs: "test"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.test.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Apply Scenario
        run: |
           pnpm dlx @embroider/try apply ${{ matrix.name }}

      - name: Install Dependencies
        run: pnpm install --no-lockfile

      - name: Run Tests
        run: |
          pnpm test

        env: ${{ matrix.env }}

  tests_ts:
    name: "Type checking: TS ${{ matrix.ts-version }}"
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        ts-version:
          - 5.5
          - 5.6
          - 5.7
          - next

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm add -D typescript@${{ matrix.ts-version }}

      - run: ./node_modules/.bin/tsc --version && ./node_modules/.bin/tsc --noEmit true --emitDeclarationOnly false

      - run: ./node_modules/.bin/tsc --noEmit true --emitDeclarationOnly false --project type-tests --rootDir "."
