name: CI

on:
  push:
    branches:
      - main
      - "v*"
    # always run CI for tags
    tags:
      - "*"
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint Addon
        run: pnpm lint
        working-directory: ember-async-data

      - name: Lint Test App
        run: pnpm lint
        working-directory: test-app

      - name: Run Tests
        run: pnpm test:ember
        working-directory: test-app

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --no-lockfile

      - name: Run Tests
        run: pnpm test:ember
        working-directory: test-app

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: "test"
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-4.8
          - ember-lts-4.12
          - ember-release
          - ember-beta
          - ember-canary
          - embroider-safe
          - embroider-optimized

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Tests
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
        working-directory: test-app

  tests_ts:
    name: "Type checking: TS ${{ matrix.ts-version }}"
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        ts-version:
          - 5.5
          - 5.6
          - 5.7
          - next

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm add -D typescript@${{ matrix.ts-version }}
        working-directory: ember-async-data

      - run: ./node_modules/.bin/tsc --version && ./node_modules/.bin/tsc --noEmit
        working-directory: ember-async-data

      - run: ./node_modules/.bin/tsc --noEmit --project type-tests
        working-directory: ember-async-data
