name: Nightly TypeScript Run

# run the typescript@next Ember Try job...
jobs:
  ts-next:
    name: typescript@next
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: volta-cli/action@v4

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - run: yarn add -D typescript@next
        working-directory: ember-async-data

      - run: yarn tsc --noEmit
        working-directory: ember-async-data

      - run: yarn tsc --noEmit --project type-tests
        working-directory: ember-async-data

# ...nightly at midnight
on:
  schedule:
    - cron: 0 0 * * *
