name: Nightly TypeScript Run

# run the typescript@next Ember Try job...
jobs:
  ts-next:
    name: typescript@next
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm add -D typescript@next
        working-directory: ember-async-data

      - run: ./node_modules/.bin/tsc --version && ./node_modules/.bin/tsc --noEmit true --emitDeclarationOnly false
        working-directory: ember-async-data

      - run: ./node_modules/.bin/tsc --noEmit true --emitDeclarationOnly false --project type-tests --rootDir "."
        working-directory: ember-async-data

# ...nightly at midnight
on:
  schedule:
    - cron: 0 0 * * *
